/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jgles2_GLES2 */

#ifndef _Included_Jgles2_GLES2
#define _Included_Jgles2_GLES2
#ifdef __cplusplus
extern "C" {
#endif
#undef Jgles2_GLES2_GL_VENDOR
#define Jgles2_GLES2_GL_VENDOR 7936L
#undef Jgles2_GLES2_GL_RENDERER
#define Jgles2_GLES2_GL_RENDERER 7937L
#undef Jgles2_GLES2_GL_VERSION
#define Jgles2_GLES2_GL_VERSION 7938L
#undef Jgles2_GLES2_GL_EXTENSIONS
#define Jgles2_GLES2_GL_EXTENSIONS 7939L
#undef Jgles2_GLES2_GL_FRAGMENT_SHADER
#define Jgles2_GLES2_GL_FRAGMENT_SHADER 35632L
#undef Jgles2_GLES2_GL_VERTEX_SHADER
#define Jgles2_GLES2_GL_VERTEX_SHADER 35633L
#undef Jgles2_GLES2_GL_MAX_VERTEX_ATTRIBS
#define Jgles2_GLES2_GL_MAX_VERTEX_ATTRIBS 34921L
#undef Jgles2_GLES2_GL_MAX_VERTEX_UNIFORM_VECTORS
#define Jgles2_GLES2_GL_MAX_VERTEX_UNIFORM_VECTORS 36347L
#undef Jgles2_GLES2_GL_MAX_VARYING_VECTORS
#define Jgles2_GLES2_GL_MAX_VARYING_VECTORS 36348L
#undef Jgles2_GLES2_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
#define Jgles2_GLES2_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 35661L
#undef Jgles2_GLES2_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
#define Jgles2_GLES2_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 35660L
#undef Jgles2_GLES2_GL_MAX_TEXTURE_IMAGE_UNITS
#define Jgles2_GLES2_GL_MAX_TEXTURE_IMAGE_UNITS 34930L
#undef Jgles2_GLES2_GL_MAX_FRAGMENT_UNIFORM_VECTORS
#define Jgles2_GLES2_GL_MAX_FRAGMENT_UNIFORM_VECTORS 36349L
#undef Jgles2_GLES2_GL_SHADER_TYPE
#define Jgles2_GLES2_GL_SHADER_TYPE 35663L
#undef Jgles2_GLES2_GL_DELETE_STATUS
#define Jgles2_GLES2_GL_DELETE_STATUS 35712L
#undef Jgles2_GLES2_GL_LINK_STATUS
#define Jgles2_GLES2_GL_LINK_STATUS 35714L
#undef Jgles2_GLES2_GL_VALIDATE_STATUS
#define Jgles2_GLES2_GL_VALIDATE_STATUS 35715L
#undef Jgles2_GLES2_GL_ATTACHED_SHADERS
#define Jgles2_GLES2_GL_ATTACHED_SHADERS 35717L
#undef Jgles2_GLES2_GL_ACTIVE_UNIFORMS
#define Jgles2_GLES2_GL_ACTIVE_UNIFORMS 35718L
#undef Jgles2_GLES2_GL_ACTIVE_UNIFORM_MAX_LENGTH
#define Jgles2_GLES2_GL_ACTIVE_UNIFORM_MAX_LENGTH 35719L
#undef Jgles2_GLES2_GL_ACTIVE_ATTRIBUTES
#define Jgles2_GLES2_GL_ACTIVE_ATTRIBUTES 35721L
#undef Jgles2_GLES2_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
#define Jgles2_GLES2_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH 35722L
#undef Jgles2_GLES2_GL_SHADING_LANGUAGE_VERSION
#define Jgles2_GLES2_GL_SHADING_LANGUAGE_VERSION 35724L
#undef Jgles2_GLES2_GL_CURRENT_PROGRAM
#define Jgles2_GLES2_GL_CURRENT_PROGRAM 35725L
#undef Jgles2_GLES2_GL_COMPILE_STATUS
#define Jgles2_GLES2_GL_COMPILE_STATUS 35713L
#undef Jgles2_GLES2_GL_INFO_LOG_LENGTH
#define Jgles2_GLES2_GL_INFO_LOG_LENGTH 35716L
#undef Jgles2_GLES2_GL_SHADER_SOURCE_LENGTH
#define Jgles2_GLES2_GL_SHADER_SOURCE_LENGTH 35720L
#undef Jgles2_GLES2_GL_SHADER_COMPILER
#define Jgles2_GLES2_GL_SHADER_COMPILER 36346L
#undef Jgles2_GLES2_GL_FALSE
#define Jgles2_GLES2_GL_FALSE 0L
#undef Jgles2_GLES2_GL_TRUE
#define Jgles2_GLES2_GL_TRUE 1L
#undef Jgles2_GLES2_GL_DEPTH_BUFFER_BIT
#define Jgles2_GLES2_GL_DEPTH_BUFFER_BIT 256L
#undef Jgles2_GLES2_GL_STENCIL_BUFFER_BIT
#define Jgles2_GLES2_GL_STENCIL_BUFFER_BIT 1024L
#undef Jgles2_GLES2_GL_COLOR_BUFFER_BIT
#define Jgles2_GLES2_GL_COLOR_BUFFER_BIT 16384L
#undef Jgles2_GLES2_GL_BYTE
#define Jgles2_GLES2_GL_BYTE 5120L
#undef Jgles2_GLES2_GL_UNSIGNED_BYTE
#define Jgles2_GLES2_GL_UNSIGNED_BYTE 5121L
#undef Jgles2_GLES2_GL_SHORT
#define Jgles2_GLES2_GL_SHORT 5122L
#undef Jgles2_GLES2_GL_UNSIGNED_SHORT
#define Jgles2_GLES2_GL_UNSIGNED_SHORT 5123L
#undef Jgles2_GLES2_GL_INT
#define Jgles2_GLES2_GL_INT 5124L
#undef Jgles2_GLES2_GL_UNSIGNED_INT
#define Jgles2_GLES2_GL_UNSIGNED_INT 5125L
#undef Jgles2_GLES2_GL_FLOAT
#define Jgles2_GLES2_GL_FLOAT 5126L
#undef Jgles2_GLES2_GL_FIXED
#define Jgles2_GLES2_GL_FIXED 5132L
#undef Jgles2_GLES2_GL_POINTS
#define Jgles2_GLES2_GL_POINTS 0L
#undef Jgles2_GLES2_GL_LINES
#define Jgles2_GLES2_GL_LINES 1L
#undef Jgles2_GLES2_GL_LINE_LOOP
#define Jgles2_GLES2_GL_LINE_LOOP 2L
#undef Jgles2_GLES2_GL_LINE_STRIP
#define Jgles2_GLES2_GL_LINE_STRIP 3L
#undef Jgles2_GLES2_GL_TRIANGLES
#define Jgles2_GLES2_GL_TRIANGLES 4L
#undef Jgles2_GLES2_GL_TRIANGLE_STRIP
#define Jgles2_GLES2_GL_TRIANGLE_STRIP 5L
#undef Jgles2_GLES2_GL_TRIANGLE_FAN
#define Jgles2_GLES2_GL_TRIANGLE_FAN 6L
/*
 * Class:     Jgles2_GLES2
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jgles2_GLES2_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     Jgles2_GLES2
 * Method:    glCreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Jgles2_GLES2_glCreateShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glShaderSource
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Jgles2_GLES2
 * Method:    glCompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glCompileShader
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glGetShaderiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glGetShaderiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     Jgles2_GLES2
 * Method:    glCreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jgles2_GLES2_glCreateProgram
  (JNIEnv *, jclass);

/*
 * Class:     Jgles2_GLES2
 * Method:    glAttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glAttachShader
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glLinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glLinkProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glGetProgramiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glGetProgramiv
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     Jgles2_GLES2
 * Method:    glGetProgramInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jgles2_GLES2_glGetProgramInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glGetShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jgles2_GLES2_glGetShaderInfoLog
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glBindAttribLocation
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glBindAttribLocation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     Jgles2_GLES2
 * Method:    glGetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Jgles2_GLES2_glGetUniformLocation
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     Jgles2_GLES2
 * Method:    glUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glUseProgram
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glViewport
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glViewport
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glDisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glDisableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glEnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glEnableVertexAttribArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glDrawArrays
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     Jgles2_GLES2
 * Method:    glVertexAttribPointer
 * Signature: (IIIIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     Jgles2_GLES2
 * Method:    glUniformMatrix4fv
 * Signature: (IIILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glUniformMatrix4fv
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     Jgles2_GLES2
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Jgles2_GLES2_glClear
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
