/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jgles2_EGL */

#ifndef _Included_Jgles2_EGL
#define _Included_Jgles2_EGL
#ifdef __cplusplus
extern "C" {
#endif
#undef Jgles2_EGL_EGL_VENDOR
#define Jgles2_EGL_EGL_VENDOR 12371L
#undef Jgles2_EGL_EGL_VERSION
#define Jgles2_EGL_EGL_VERSION 12372L
#undef Jgles2_EGL_EGL_EXTENSIONS
#define Jgles2_EGL_EGL_EXTENSIONS 12373L
#undef Jgles2_EGL_EGL_CLIENT_APIS
#define Jgles2_EGL_EGL_CLIENT_APIS 12429L
#undef Jgles2_EGL_EGL_BUFFER_SIZE
#define Jgles2_EGL_EGL_BUFFER_SIZE 12320L
#undef Jgles2_EGL_EGL_ALPHA_SIZE
#define Jgles2_EGL_EGL_ALPHA_SIZE 12321L
#undef Jgles2_EGL_EGL_BLUE_SIZE
#define Jgles2_EGL_EGL_BLUE_SIZE 12322L
#undef Jgles2_EGL_EGL_GREEN_SIZE
#define Jgles2_EGL_EGL_GREEN_SIZE 12323L
#undef Jgles2_EGL_EGL_RED_SIZE
#define Jgles2_EGL_EGL_RED_SIZE 12324L
#undef Jgles2_EGL_EGL_DEPTH_SIZE
#define Jgles2_EGL_EGL_DEPTH_SIZE 12325L
#undef Jgles2_EGL_EGL_STENCIL_SIZE
#define Jgles2_EGL_EGL_STENCIL_SIZE 12326L
#undef Jgles2_EGL_EGL_CONFIG_CAVEAT
#define Jgles2_EGL_EGL_CONFIG_CAVEAT 12327L
#undef Jgles2_EGL_EGL_CONFIG_ID
#define Jgles2_EGL_EGL_CONFIG_ID 12328L
#undef Jgles2_EGL_EGL_LEVEL
#define Jgles2_EGL_EGL_LEVEL 12329L
#undef Jgles2_EGL_EGL_MAX_PBUFFER_HEIGHT
#define Jgles2_EGL_EGL_MAX_PBUFFER_HEIGHT 12330L
#undef Jgles2_EGL_EGL_MAX_PBUFFER_PIXELS
#define Jgles2_EGL_EGL_MAX_PBUFFER_PIXELS 12331L
#undef Jgles2_EGL_EGL_MAX_PBUFFER_WIDTH
#define Jgles2_EGL_EGL_MAX_PBUFFER_WIDTH 12332L
#undef Jgles2_EGL_EGL_NATIVE_RENDERABLE
#define Jgles2_EGL_EGL_NATIVE_RENDERABLE 12333L
#undef Jgles2_EGL_EGL_NATIVE_VISUAL_ID
#define Jgles2_EGL_EGL_NATIVE_VISUAL_ID 12334L
#undef Jgles2_EGL_EGL_NATIVE_VISUAL_TYPE
#define Jgles2_EGL_EGL_NATIVE_VISUAL_TYPE 12335L
#undef Jgles2_EGL_EGL_SAMPLES
#define Jgles2_EGL_EGL_SAMPLES 12337L
#undef Jgles2_EGL_EGL_SAMPLE_BUFFERS
#define Jgles2_EGL_EGL_SAMPLE_BUFFERS 12338L
#undef Jgles2_EGL_EGL_SURFACE_TYPE
#define Jgles2_EGL_EGL_SURFACE_TYPE 12339L
#undef Jgles2_EGL_EGL_TRANSPARENT_TYPE
#define Jgles2_EGL_EGL_TRANSPARENT_TYPE 12340L
#undef Jgles2_EGL_EGL_TRANSPARENT_BLUE_VALUE
#define Jgles2_EGL_EGL_TRANSPARENT_BLUE_VALUE 12341L
#undef Jgles2_EGL_EGL_TRANSPARENT_GREEN_VALUE
#define Jgles2_EGL_EGL_TRANSPARENT_GREEN_VALUE 12342L
#undef Jgles2_EGL_EGL_TRANSPARENT_RED_VALUE
#define Jgles2_EGL_EGL_TRANSPARENT_RED_VALUE 12343L
#undef Jgles2_EGL_EGL_NONE
#define Jgles2_EGL_EGL_NONE 12344L
#undef Jgles2_EGL_EGL_BIND_TO_TEXTURE_RGB
#define Jgles2_EGL_EGL_BIND_TO_TEXTURE_RGB 12345L
#undef Jgles2_EGL_EGL_BIND_TO_TEXTURE_RGBA
#define Jgles2_EGL_EGL_BIND_TO_TEXTURE_RGBA 12346L
#undef Jgles2_EGL_EGL_MIN_SWAP_INTERVAL
#define Jgles2_EGL_EGL_MIN_SWAP_INTERVAL 12347L
#undef Jgles2_EGL_EGL_MAX_SWAP_INTERVAL
#define Jgles2_EGL_EGL_MAX_SWAP_INTERVAL 12348L
#undef Jgles2_EGL_EGL_LUMINANCE_SIZE
#define Jgles2_EGL_EGL_LUMINANCE_SIZE 12349L
#undef Jgles2_EGL_EGL_ALPHA_MASK_SIZE
#define Jgles2_EGL_EGL_ALPHA_MASK_SIZE 12350L
#undef Jgles2_EGL_EGL_COLOR_BUFFER_TYPE
#define Jgles2_EGL_EGL_COLOR_BUFFER_TYPE 12351L
#undef Jgles2_EGL_EGL_RENDERABLE_TYPE
#define Jgles2_EGL_EGL_RENDERABLE_TYPE 12352L
#undef Jgles2_EGL_EGL_MATCH_NATIVE_PIXMAP
#define Jgles2_EGL_EGL_MATCH_NATIVE_PIXMAP 12353L
#undef Jgles2_EGL_EGL_CONFORMANT
#define Jgles2_EGL_EGL_CONFORMANT 12354L
#undef Jgles2_EGL_EGL_SLOW_CONFIG
#define Jgles2_EGL_EGL_SLOW_CONFIG 12368L
#undef Jgles2_EGL_EGL_NON_CONFORMANT_CONFIG
#define Jgles2_EGL_EGL_NON_CONFORMANT_CONFIG 12369L
#undef Jgles2_EGL_EGL_TRANSPARENT_RGB
#define Jgles2_EGL_EGL_TRANSPARENT_RGB 12370L
#undef Jgles2_EGL_EGL_RGB_BUFFER
#define Jgles2_EGL_EGL_RGB_BUFFER 12430L
#undef Jgles2_EGL_EGL_LUMINANCE_BUFFER
#define Jgles2_EGL_EGL_LUMINANCE_BUFFER 12431L
#undef Jgles2_EGL_EGL_NO_TEXTURE
#define Jgles2_EGL_EGL_NO_TEXTURE 12380L
#undef Jgles2_EGL_EGL_TEXTURE_RGB
#define Jgles2_EGL_EGL_TEXTURE_RGB 12381L
#undef Jgles2_EGL_EGL_TEXTURE_RGBA
#define Jgles2_EGL_EGL_TEXTURE_RGBA 12382L
#undef Jgles2_EGL_EGL_TEXTURE_2D
#define Jgles2_EGL_EGL_TEXTURE_2D 12383L
#undef Jgles2_EGL_EGL_PBUFFER_BIT
#define Jgles2_EGL_EGL_PBUFFER_BIT 1L
#undef Jgles2_EGL_EGL_PIXMAP_BIT
#define Jgles2_EGL_EGL_PIXMAP_BIT 2L
#undef Jgles2_EGL_EGL_WINDOW_BIT
#define Jgles2_EGL_EGL_WINDOW_BIT 4L
#undef Jgles2_EGL_EGL_VG_COLORSPACE_LINEAR_BIT
#define Jgles2_EGL_EGL_VG_COLORSPACE_LINEAR_BIT 32L
#undef Jgles2_EGL_EGL_VG_ALPHA_FORMAT_PRE_BIT
#define Jgles2_EGL_EGL_VG_ALPHA_FORMAT_PRE_BIT 64L
#undef Jgles2_EGL_EGL_MULTISAMPLE_RESOLVE_BOX_BIT
#define Jgles2_EGL_EGL_MULTISAMPLE_RESOLVE_BOX_BIT 512L
#undef Jgles2_EGL_EGL_SWAP_BEHAVIOR_PRESERVED_BIT
#define Jgles2_EGL_EGL_SWAP_BEHAVIOR_PRESERVED_BIT 1024L
#undef Jgles2_EGL_EGL_OPENGL_ES_BIT
#define Jgles2_EGL_EGL_OPENGL_ES_BIT 1L
#undef Jgles2_EGL_EGL_OPENVG_BIT
#define Jgles2_EGL_EGL_OPENVG_BIT 2L
#undef Jgles2_EGL_EGL_OPENGL_ES2_BIT
#define Jgles2_EGL_EGL_OPENGL_ES2_BIT 4L
#undef Jgles2_EGL_EGL_OPENGL_BIT
#define Jgles2_EGL_EGL_OPENGL_BIT 8L
#undef Jgles2_EGL_EGL_DEFAULT_DISPLAY
#define Jgles2_EGL_EGL_DEFAULT_DISPLAY 0LL
#undef Jgles2_EGL_EGL_NO_CONTEXT
#define Jgles2_EGL_EGL_NO_CONTEXT 0LL
#undef Jgles2_EGL_EGL_NO_DISPLAY
#define Jgles2_EGL_EGL_NO_DISPLAY 0LL
#undef Jgles2_EGL_EGL_NO_SURFACE
#define Jgles2_EGL_EGL_NO_SURFACE 0LL
#undef Jgles2_EGL_EGL_CONTEXT_CLIENT_VERSION
#define Jgles2_EGL_EGL_CONTEXT_CLIENT_VERSION 12440L
#undef Jgles2_EGL_EGL_HEIGHT
#define Jgles2_EGL_EGL_HEIGHT 12374L
#undef Jgles2_EGL_EGL_WIDTH
#define Jgles2_EGL_EGL_WIDTH 12375L
#undef Jgles2_EGL_EGL_LARGEST_PBUFFER
#define Jgles2_EGL_EGL_LARGEST_PBUFFER 12376L
#undef Jgles2_EGL_EGL_TEXTURE_FORMAT
#define Jgles2_EGL_EGL_TEXTURE_FORMAT 12416L
#undef Jgles2_EGL_EGL_TEXTURE_TARGET
#define Jgles2_EGL_EGL_TEXTURE_TARGET 12417L
#undef Jgles2_EGL_EGL_MIPMAP_TEXTURE
#define Jgles2_EGL_EGL_MIPMAP_TEXTURE 12418L
#undef Jgles2_EGL_EGL_MIPMAP_LEVEL
#define Jgles2_EGL_EGL_MIPMAP_LEVEL 12419L
#undef Jgles2_EGL_EGL_RENDER_BUFFER
#define Jgles2_EGL_EGL_RENDER_BUFFER 12422L
#undef Jgles2_EGL_EGL_VG_COLORSPACE
#define Jgles2_EGL_EGL_VG_COLORSPACE 12423L
#undef Jgles2_EGL_EGL_VG_ALPHA_FORMAT
#define Jgles2_EGL_EGL_VG_ALPHA_FORMAT 12424L
#undef Jgles2_EGL_EGL_HORIZONTAL_RESOLUTION
#define Jgles2_EGL_EGL_HORIZONTAL_RESOLUTION 12432L
#undef Jgles2_EGL_EGL_VERTICAL_RESOLUTION
#define Jgles2_EGL_EGL_VERTICAL_RESOLUTION 12433L
#undef Jgles2_EGL_EGL_PIXEL_ASPECT_RATIO
#define Jgles2_EGL_EGL_PIXEL_ASPECT_RATIO 12434L
#undef Jgles2_EGL_EGL_SWAP_BEHAVIOR
#define Jgles2_EGL_EGL_SWAP_BEHAVIOR 12435L
#undef Jgles2_EGL_EGL_MULTISAMPLE_RESOLVE
#define Jgles2_EGL_EGL_MULTISAMPLE_RESOLVE 12441L
/*
 * Class:     Jgles2_EGL
 * Method:    eglGetDisplay
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Jgles2_EGL_eglGetDisplay
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Jgles2_EGL
 * Method:    eglInitialize
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Jgles2_EGL_eglInitialize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Jgles2_EGL
 * Method:    eglQueryString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Jgles2_EGL_eglQueryString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     Jgles2_EGL
 * Method:    eglChooseConfig
 * Signature: (JLjava/nio/IntBuffer;Ljava/nio/LongBuffer;ILjava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_Jgles2_EGL_eglChooseConfig
  (JNIEnv *, jclass, jlong, jobject, jobject, jint, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglCreateContext
 * Signature: (JJJLjava/nio/IntBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_Jgles2_EGL_eglCreateContext
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglQueryContext
 * Signature: (JJILjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_Jgles2_EGL_eglQueryContext
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglCreateWindowSurface
 * Signature: (JJJLjava/nio/IntBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_Jgles2_EGL_eglCreateWindowSurface
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglQuerySurface
 * Signature: (JJILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_EGL_eglQuerySurface
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglGetConfigAttrib
 * Signature: (JJILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_Jgles2_EGL_eglGetConfigAttrib
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     Jgles2_EGL
 * Method:    eglMakeCurrent
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_Jgles2_EGL_eglMakeCurrent
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     Jgles2_EGL
 * Method:    eglGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Jgles2_EGL_eglGetError
  (JNIEnv *, jclass);

/*
 * Class:     Jgles2_EGL
 * Method:    eglSwapBuffers
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_Jgles2_EGL_eglSwapBuffers
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
