/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jgles2_util */

#ifndef _Included_Jgles2_util
#define _Included_Jgles2_util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jgles2_util
 * Method:    get_native_display
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Jgles2_util_get_1native_1display
  (JNIEnv *, jclass);

/*
 * Class:     Jgles2_util
 * Method:    make_native_window
 * Signature: (JJJIIIIZ)J
 */
JNIEXPORT jlong JNICALL Java_Jgles2_util_make_1native_1window
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
